#!/bin/sh

# Wifi
if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
	icon="🌐"
elif [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ] ; then
    icon="🌐"
elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] ; then
	[ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = '0x1003' ] && icon="🌐" || icon="❌"
else
	icon="❌"
fi

printf "%s\n" "$icon"
