Section "Device"
    Identifier "Framebuffer"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "Generic Monitor"
    ModelName "LCD Monitor"
    DisplaySize 320 320
EndSection

Section "Screen"
    Identifier "Default Screen"
    Device "Framebuffer"
    Monitor "Generic Monitor"
EndSection
